2018-04-04 22:20:38,629-'test'-INFO-now test case1
2018-04-04 22:20:39,648-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/getBookList (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE3C834C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001DE3C836448>)
2018-04-04 22:20:39,648-'test'-INFO-now test case2
2018-04-04 22:20:40,666-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/addBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE3C84E5F8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001DE3C84A688>)
2018-04-04 22:20:40,666-'test'-INFO-now test case3
2018-04-04 22:20:41,686-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/addBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE3C84ECC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001DE3C836E08>)
2018-04-04 22:20:41,687-'test'-INFO-now test case4
2018-04-04 22:20:42,696-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/updateBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE3C858400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001DE3C84AFC8>)
2018-04-04 22:20:42,697-'test'-INFO-now test case5
2018-04-04 22:20:43,707-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/updateBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE3C818F98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001DE3C852848>)
2018-04-04 22:20:43,707-'test'-INFO-now test case6
2018-04-04 22:20:44,713-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/deleteBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE3C858550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001DE3C852E48>)
2018-04-04 22:20:44,714-'test'-INFO-now test case7
2018-04-04 22:20:45,720-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/deleteBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DE3C858BA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001DE3C84A748>)
