2018-04-04 22:18:23,597-'test'-INFO-now test case1
2018-04-04 22:18:24,618-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/getBookList (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC2D6F4C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001BC2D6F6448>)
2018-04-04 22:18:24,619-'test'-INFO-now test case2
2018-04-04 22:18:25,623-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/addBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC2D70E5F8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001BC2D70A688>)
2018-04-04 22:18:25,623-'test'-INFO-now test case3
2018-04-04 22:18:26,631-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/addBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC2D70ECC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001BC2D6F6E08>)
2018-04-04 22:18:26,631-'test'-INFO-now test case4
2018-04-04 22:18:27,646-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/updateBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC2D718400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001BC2D70AFC8>)
2018-04-04 22:18:27,646-'test'-INFO-now test case5
2018-04-04 22:18:28,661-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/updateBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC2D6D8F98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001BC2D712848>)
2018-04-04 22:18:28,661-'test'-INFO-now test case6
2018-04-04 22:18:29,677-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/deleteBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC2D718550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001BC2D712E48>)
2018-04-04 22:18:29,677-'test'-INFO-now test case7
2018-04-04 22:18:30,686-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/deleteBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC2D718BA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x000001BC2D70A748>)
