2018-04-04 22:15:18,565-'test'-INFO-now test case1
2018-04-04 22:15:19,589-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/getBookList (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237D4A04C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x00000237D4A06448>)
2018-04-04 22:15:19,589-'test'-INFO-now test case2
2018-04-04 22:15:20,610-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/addBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237D4A1E5F8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x00000237D4A1A688>)
2018-04-04 22:15:20,610-'test'-INFO-now test case3
2018-04-04 22:15:21,621-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/addBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237D4A1ECC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x00000237D4A06E08>)
2018-04-04 22:15:21,621-'test'-INFO-now test case4
2018-04-04 22:15:22,631-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/updateBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237D4A28400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x00000237D4A1AFC8>)
2018-04-04 22:15:22,631-'test'-INFO-now test case5
2018-04-04 22:15:23,636-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/updateBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237D49E8F98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x00000237D4A22848>)
2018-04-04 22:15:23,636-'test'-INFO-now test case6
2018-04-04 22:15:24,646-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/deleteBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237D4A28550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x00000237D4A22E48>)
2018-04-04 22:15:24,647-'test'-INFO-now test case7
2018-04-04 22:15:25,652-'test'-INFO-(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /test/book/deleteBook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237D4A28BA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",),), <traceback object at 0x00000237D4A1A748>)
